### ISSUE TITLE
ADmad/CakePHP-HybridAuth

### ISSUE THREAD

**Issue by SunilNoto** [ADmad/CakePHP-HybridAuth#101]
Anyone  can explain below code

$this->loadComponent('Auth', [
    'authenticate' => [
        'Form',
        'ADmad/HybridAuth.HybridAuth' => [
            // All keys shown below are defaults
            'fields' => [
                'provider' => 'provider',
                'openid_identifier' => 'openid_identifier',
                'email' => 'email'
            ],

            'profileModel' => 'ADmad/HybridAuth.SocialProfiles',
            'profileModelFkField' => 'user_id',

            'userModel' => 'Users',

            // The URL Hybridauth lib should redirect to after authentication.
            // If no value is specified you are redirect to this plugin's
            // HybridAuthController::authenticated() which handles persisting
            // user info to AuthComponent and redirection.
            'hauth_return_to' => null
        ]
    ]
]);

Note: When specifying loginRedirect URL for AuthComponent be sure to add 'plugin' => false (or appropiate plugin name) to the URL array.

and I am using Users Controller and use below action

public function login() {
    if ($this->request->is('post')) {
        $user = $this->Auth->identify();
        if ($user) {
            $this->Auth->setUser($user);
            return $this->redirect($this->Auth->redirectUrl());
        }
        $this->Flash->error(__('Invalid username or password, try again'));
    }
}

And getting error 

![error_missing_route_-_2017-05-03_11 27 09](https://cloud.githubusercontent.com/assets/28335982/25650156/ac2ef73a-2ff8-11e7-9dd3-84089d206668.png)

**Comment by ADmad** [comment]
Specify `loginAction` URL in `AuthComponent` config with `'plugin' => false`.
