### ISSUE TITLE
Differentiate between the user who signs in or up

### ISSUE THREAD

**Issue by gonzela2006** [ADmad/CakePHP-HybridAuth#108]
Hi,

I have an option for my app to close new registrations. How can I differentiate between the user who signs in or signs up so I can prevent sign ups when close registration is active?

Thanks

**Comment by ADmad** [comment]
For new social logins `HybridAuth.newUser ` event is triggered for which you need to set listener. So when you have registrations turned off just throw an exception from the event's callback instead of returning new user record.

**Comment by gonzela2006** [comment]
@ADmad Thank you. I already added event's callback into `users` table but I'd like to make a redirect with a flash error message instead of exception but $this->redirect not work on models

**Comment by ADmad** [comment]
You can use a custom exception and custom exception handler method where you can do the redirect.

**Comment by gonzela2006** [comment]
Can you share a link so I can learn how to do this, please?

**Comment by ADmad** [comment]
https://book.cakephp.org/3.0/en/development/errors.html#creating-your-own-application-exceptions
https://book.cakephp.org/3.0/en/development/errors.html#using-the-exceptionrenderer-option-of-the-default-handler

**Comment by gonzela2006** [comment]
@ADmad Thanks, much appreciated.
