### ISSUE TITLE
Why HybridAuth.SocialProfiles hasMany instead of belongsTo or hasOne ..?

### ISSUE THREAD

**Issue by EOM** [ADmad/CakePHP-HybridAuth#109]
`Hi,`
Because in the example you make a **hasMany** link instead of **belongsTo** or **hasOne** ..?

        // Plugin Social HybridAuth.SocialProfiles
//        $this->hasMany('ADmad/HybridAuth.SocialProfiles');

        $this->belongsTo('ADmad/HybridAuth.SocialProfiles', [
            'foreignKey' => 'social_profiles_id',
            'joinType' => 'LEFT'
        ]);
OR

`$this->hasOne('ADmad/HybridAuth.SocialProfiles');`

**Comment by ADmad** [comment]
Each user can have multiple social profiles. For e.g. you can have Google and Facebook account and can use either to login to the site but both profiles should be associated with same user account.

**Comment by EOM** [comment]
Ahhh ok
But in my case the user only has a social profile, `User 1 <=> 1 SocialProfiles`.
No problem using `$this->hasOne('ADmad / HybridAuth.SocialProfiles');`
Because from what I saw, it works for me. And if it works well this is good in the documentation also to facilitate the task to other users.
