### ISSUE TITLE
Unable to access `redirectUrl()`

### ISSUE THREAD

**Issue by chrisvogt** [ADmad/CakePHP-HybridAuth#11]
I've run into the following fatal error attempting to login after installing HybridAuth:

    Notice (8): Undefined property: HybridAuthAuthenticate::$_registry [ROOT/Plugin/HybridAuth/Controller/Component/Auth/HybridAuthAuthenticate.php, line 104]
    Notice (8): Trying to get property of non-object [ROOT/Plugin/HybridAuth/Controller/Component/Auth/HybridAuthAuthenticate.php, line 104]

I rolled my version of Cake back to the 2.4 branch to check if this might be a result of any core changes that have happened since, but I see the same error whether using 2.4, 2.5, or 2.6. 

To fix this I access the Auth settings through `$this->_Collection` instead of `$this->_registry`. I will submit a PR with these changes now, but please let me know if I'm doing something wrong on my end to run into this issue.

(P.S., I now realize I have only tested this on top of the [FriendsOfCake/app-template](https://github.com/FriendsOfCake/app-template) project skeleton. I'm going to double-check this with a :icecream: install of Cake and report back here if I run into the same issue.)

**Comment by ADmad** [comment]
Closing as #12 is opened with fix.

**Comment by chrisvogt** [comment]
Confirmed I also see this issue on a vanilla install of Cake, without using app-template. (Before applying the fix, that is.)
