### ISSUE TITLE
Unable to login through facebook

### ISSUE THREAD

**Issue by sahdev0** [ADmad/CakePHP-HybridAuth#110]
Hello sir,

I had configured cakephp-hybridauth plugin one of my vod-platform project,  works perfectly but suddenly it stopped and I am getting ( invalid username and password) my custom message and can't indentify using $this->Auth->identify(). It returns null.

Cakephp version: 3.3.*

My setup is below:

**config/hybridauth.php**

    use Cake\Core\Configure;

    return [
    'HybridAuth' => [
        'providers' => [

            'Facebook' => [
                'enabled' => true,
                'keys' => [
                    'id' => '271323359952642',
                    'secret' => '1c9d816f491daa96b056102a0291ca15'
                ],
                'scope' => 'email, user_about_me, user_birthday, user_hometown',
                // 'trustForwarded'=>true
            ]
        ],
        'debug_mode' => Configure::read('debug'),
        'debug_file' => LOGS . 'hybridauth.log',
    ]
    ];

**src/AppController.php**

     $this->loadComponent('Auth', [
            'authorize'=>['Controller'],
            'loginRedirect' => [
                'controller' => 'Users',
                'action' => 'dashboard',
                'plugin' => false,
                'ADmad/HybridAuth.HybridAuth' => false
            ],
            'logoutRedirect' => [
                'controller' => 'Users',
                'action' => 'dashboard'
            ],
            'authenticate' => [
            'Form',
            'ADmad/HybridAuth.HybridAuth' => [
                // All keys shown below are defaults
                'fields' => [
                    'provider' => 'provider',
                    'openid_identifier' => 'openid_identifier',
                    'email' => 'email'
                ],
                'profileModel' => 'ADmad/HybridAuth.SocialProfiles',
                'profileModelFkField' => 'user_id',
                'userModel' => 'Users',
                'hauth_return_to' => null
            ]
        ]

        ]);

request url:

     echo $this->Form->postLink(
				    '<i class="fa fa-facebook"></i> Login with Facebook',
				    	[
				    		'controller' => 'Users', 
				    		'action' => 'login', 
				    		'?' => ['provider' => 'Facebook']
				    	],
				    	['escape'=>false]
				);

**Comment by sanjib-dev** [comment]
Have you update hybrid auth to the latest version ?
Facebook has changed it sometime back.
If so kindly post the exact error

**Comment by sahdev0** [comment]
ok. How can i upgrade single plugin in my project. should i download and copy on that location or have any bake command to upgrade plugin in cakephp 3.

**Comment by sanjib-dev** [comment]
Cake php is composer driven and all you need to do is update that plugin
with it.
Also, you can update ur local copy and manually copy paste it into your
live code.

**Comment by sahdev0** [comment]
ok let me try this approach.
thanks

**Comment by sahdev0** [comment]
I updated my hybrid-auth plugin manually. But still not able to login through facebook.

**Comment by sanjib-dev** [comment]
What is the exact error u r getting

On 08-Sep-2017 18:41, "Sahadev Sahu" <notifications@github.com> wrote:

I updated my hybrid-auth plugin manually. But still not able to login
through facebook.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ADmad/CakePHP-HybridAuth/issues/110#issuecomment-328099345>,
or mute the thread

**Comment by sahdev0** [comment]
i cant update my complete project so i only updated hybridauth plugin in my local system and copy and paste admad directory on server code and checked facebook login but unable to login and not gatting any error. Is there any mistake from my side or can you please guide me how can i update my hybridauth plugin.

**Comment by sanjib-dev** [comment]
Update the hybrid auth with same process
