### ISSUE TITLE
Undefined index: login_done

### ISSUE THREAD

**Issue by priyankamackwan** [ADmad/CakePHP-HybridAuth#112]
Getting error " Undefined index: login_done in [vendor/hybridauth/hybridauth/hybridauth/Hybrid/Providers/Facebook.php" while using this plugin for Signup through facebook.

Please help

**Comment by sebagr** [comment]
I know this issue is old, but I'm still seeing it only on some logins. Any idea why this happens?

**Comment by ADmad** [comment]
I have no idea. Given that the error occurs in the Hybrid Auth lib's code there's isn't much I can do anyway.
