### ISSUE TITLE
hybridauth v2.10.0 class 'Hybrid_Auth' not found 

### ISSUE THREAD

**Issue by aceat64** [ADmad/CakePHP-HybridAuth#113]
Something changed upstream between v2.9.6 and v2.10.0 that causes the following error:

> Class 'Hybrid_Auth' not found
> Error in: ROOT/vendor/admad/cakephp-hybridauth/src/Auth/HybridAuthAuthenticate.php, line 129
> 
>     ⟩ ADmad\HybridAuth\Auth\HybridAuthAuthenticate->_init ROOT/vendor/admad/cakephp-hybridauth/src/Auth/HybridAuthAuthenticate.php, line 178
>     ⟩ ADmad\HybridAuth\Auth\HybridAuthAuthenticate->getUser CORE/src/Controller/Component/AuthComponent.php, line 715
>     ⟩ Cake\Controller\Component\AuthComponent->_getUser CORE/src/Controller/Component/AuthComponent.php, line 295
>     ⟩ Cake\Controller\Component\AuthComponent->authCheck CORE/src/Controller/Component/AuthComponent.php, line 260
>     ⟩ Cake\Controller\Component\AuthComponent->startup CORE/src/Event/EventManager.php, line 422
>     ⟩ Cake\Event\EventManager->_callListener CORE/src/Event/EventManager.php, line 391
>     ⟩ Cake\Event\EventManager->dispatch CORE/src/Event/EventDispatcherTrait.php, line 78
>     ⟩ Cake\Controller\Controller->dispatchEvent CORE/src/Controller/Controller.php, line 501
>     ⟩ Cake\Controller\Controller->startupProcess CORE/src/Http/ActionDispatcher.php, line 116
>     ⟩ Cake\Http\ActionDispatcher->_invoke CORE/src/Http/ActionDispatcher.php, line 95
>     ⟩ Cake\Http\ActionDispatcher->dispatch CORE/src/Http/BaseApplication.php, line 83
>     ⟩ Cake\Http\BaseApplication->__invoke CORE/src/Http/Runner.php, line 65
>     ⟩ Cake\Http\Runner->__invoke CORE/src/Routing/Middleware/RoutingMiddleware.php, line 62
>     ⟩ Cake\Routing\Middleware\RoutingMiddleware->__invoke CORE/src/Http/Runner.php, line 65
>     ⟩ Cake\Http\Runner->__invoke CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
>     ⟩ Cake\Routing\Middleware\AssetMiddleware->__invoke CORE/src/Http/Runner.php, line 65
>     ⟩ Cake\Http\Runner->__invoke CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 81
>     ⟩ Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke CORE/src/Http/Runner.php, line 65
>     ⟩ Cake\Http\Runner->__invoke CORE/src/Http/Runner.php, line 51
>     ⟩ Cake\Http\Runner->run CORE/src/Http/Server.php, line 90
>     ⟩ Cake\Http\Server->run ROOT/webroot/index.php, line 37
>

**Comment by ADmad** [comment]
A PR to fix the issue is welcome.

HybridAuth is a pain in the ass, why is why I made a new plugin [admad/cakephp-social-auth](https://github.com/ADmad/cakephp-social-auth) for social logins.

**Comment by aceat64** [comment]
Looks like this was fixed upstream, they tagged the wrong commit for release:

https://github.com/hybridauth/hybridauth/issues/879
