### ISSUE TITLE
Redirect to an additional form page after Authentication.

### ISSUE THREAD

**Issue by yoshitakameg** [ADmad/CakePHP-HybridAuth#114]
Hi, I would like to have a page, which asks users to input additional profile info, after authentication.
Facebook user info have first name and last name, but Twitter user info don't, but I want to save the same info to database.
The page flow that I am thinking is something like this:
1. Login page(click 'Login with Twitter account') ->
2. Twitter authentication page(allow using the profile info) -> 
3. Additional info input page(input additional info like first and last name, then click send) ->
4. LoginRedirect page.

Would anyone please help me out to make it possible?

**Comment by sanjib-dev** [comment]
just a thought..
you could have a check after login that if certain information is not there users are redirected to a update profile page. so its a general redirection(your loginredirect url will same for all) and when user logs in with social profiles it will also work.
meanwhile, this is not a bug :)

**Comment by ADmad** [comment]
>  you could have a check after login that if certain information is not there users are redirected to a update profile page. so its a general redirection(your loginredirect url will same for all) and when user logs in with social profiles it will also work.

This.
