### ISSUE TITLE
i need user friend list. it's possible

### ISSUE THREAD

**Issue by tilakghori** [ADmad/CakePHP-HybridAuth#115]
I use FB login. it is possible to get user friend list..?

**Comment by ADmad** [comment]
This plugin is only for handling authentication.

**Comment by tilakghori** [comment]
path: admad/cakephp-hybridauth/src/Auth/HybridAuthAuthenticate.php in 

`    protected function _getUser($adapter)
    {
        try {
            $providerProfile = $adapter->getUserProfile();
            
            $providerfriends = $adapter->getUserContacts(); // add this $providerfriends in your friend list
.......more code
`
