### ISSUE TITLE
Problem with database migration

### ISSUE THREAD

**Issue by kmcgowan0** [ADmad/CakePHP-HybridAuth#117]
I'm currently getting an 'access denied' error when I run the database migration `bin/cake migrations migrate -p ADmad/HybridAuth`
Checking the error log, it looks like this is happening because it's trying to connect to a database that doesn't exist. Is there somewhere I can modify the database that the migration uses?

Thanks

**Comment by ADmad** [comment]
Check the migration plugin documentation.
