### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by natzar** [ADmad/CakePHP-HybridAuth#124]
I was using it in production, but suddenly it stopped working. Have LinkedIn updated something in their side? 

👉👈Would be this project updated anytime soon, please?

**Comment by ADmad** [comment]
You should check [hybridauth](https://github.com/hybridauth/hybridauth)'s issue tracker and ensure it doesn't have problem with LinkedIn.

**Comment by ADmad** [comment]
> [LinkedIn] Upgrade API to v2. (@ApacheEx)

https://github.com/hybridauth/hybridauth/releases/tag/v2.15.0

So update hybridauth to latest 2.x version.
