### ISSUE TITLE
[request] - Make Cake3 branch the master

### ISSUE THREAD

**Issue by thinkingmedia** [ADmad/CakePHP-HybridAuth#22]
Now that CakePHP 3.0 is released. Can the Cake3 branch become the master, and the master be branched for Cake2.

I'm not sure how this would impact composer, but Cake2 doesn't use composer. So people would just have to remove the branch reference.

The plugin should maybe use a release tag as well.

**Comment by ADmad** [comment]
Current master branch for 2.x already has composer support. So it will have to be tagged before merging the cake3 branch to master. It will impact current users who users who use the master branch through composer. They will have to change "dev-master" to new release. I shouldn't have started tagging releases earlier :stuck_out_tongue:

**Comment by ADmad** [comment]
I see hybridauth 2.4 has been released so dependency version for it should be updated too.

**Comment by thinkingmedia** [comment]
If you change the composer.json file to point to tagged releases then it won't matter what branch they are from. You can then release a 2 and 3 version of the plugin.

If people have their composer.lock pointing to the master then I'm not sure what can be done. If you switch the master over to cake3 it's going to break everyones projects when they update.

When I look at my lock file it's referencing a commit hash on the branch.

Oh man, I've made the same mistake on my shared packages. So you're not alone.

**Comment by ADmad** [comment]
Releases done and cake3 merged to master.
