### ISSUE TITLE
Use an event instead of `registrationCallback` config.

### ISSUE THREAD

**Issue by ADmad** [ADmad/CakePHP-HybridAuth#25]

**Comment by thinkingmedia** [comment]
I can do this. What do you want to call the event?

**Comment by ADmad** [comment]
How about `HybridAuth.newUser`? We can always rename before merging :)

**Comment by thinkingmedia** [comment]
I guess it could be configurable as a component settings with a default. I started another website project using this plugin. So I'll add this. Do you think we could have a way of letting the User model handle lookups of user records?

**Comment by ADmad** [comment]
> I guess it could be configurable as a component settings with a default.

There's no need for it to be configurable.

> Do you think we could have a way of letting the User model handle lookups of user records?

Not sure what you mean.

**Comment by ADmad** [comment]
@thinkingmedia Ping

**Comment by thinkingmedia** [comment]
Sorry, I got distracted. I'll make a pull request to fix this as soon as I can. There is a project that I want to add to my portfolio that will use this plugin. It needs to cleaning up and when I do that work I'll make a pull request for this.

**Comment by ADmad** [comment]
No rush, thanks.

**Comment by ADmad** [comment]
Done. https://github.com/ADmad/CakePHP-HybridAuth/tree/event

**Comment by damianoporta** [comment]
@ADmad do you merge in on master?

**Comment by ADmad** [comment]
@damianoporta No I haven't.

**Comment by damianoporta** [comment]
@ADmad I found a problem with the event. You have used `$this->eventManager()->on('HybridAuth.newUser', ....);` this does not work because the event is triggered against `HybridAuthAuthenticate` object. We should use the global eventmanager object, something like:

`EventManager::instanced()->on('HybridAuth.newUser', ....);`

Or you should change `$this->dispatchEvent()` inside the HybridAuthAuthenticate.php to send the event to controller directly, something like `$this->_registry->dispatchEvent(...);`

Make sense?

**Comment by ADmad** [comment]
@damianoporta Using the global event manager provides more flexibility.

**Comment by ADmad** [comment]
@damianoporta Just in case you are interested I have put up a new 4.0 branch which support multiple providers per user. I haven't updated the readme yet but for the default config to work it only creating a `social_profiles` table (migration file is provided) and setting `$this->hasMany('ADmad/HybridAuth.SocialProfiles')` in your `UsersTable::initialize()`

**Comment by damianoporta** [comment]
@admad oh perfect! Thats a very good feature! I will see it for sure.

Admad out of curiosity why did you not merge the event branch on master? Does it have problems?

**Comment by ADmad** [comment]
I hadn't tested if properly that's why. As you found out the readme wasn't accurate :)  Now with the new 4.0 branch up I will probably drop the event branch.

**Comment by damianoporta** [comment]
@admad :) ok i will set that branch on my composer. Please could you add it on packagist?

Ok, however the event approach is a way better then simple callbacks.

**Comment by damianoporta** [comment]
@ADmad where is the migration file ?

**Comment by ADmad** [comment]
@damianoporta Every branch is automatically available through packagist :)  Use version `4.0.x-dev`.  Migrations file is under [config/Migrations](https://github.com/ADmad/CakePHP-HybridAuth/tree/4.0/config/Migrations) as usual.

**Comment by damianoporta** [comment]
Ops nevermind :)
