### ISSUE TITLE
[bug] Should fetch user entity as an array.

### ISSUE THREAD

**Issue by thinkingmedia** [ADmad/CakePHP-HybridAuth#27]
`HybridAuthAuthenticate` current fetches the user record as an CakePHP entity. This causes the `AuthComponent` to return the user record as an entity for the first time, but later when the user is fetched from the session it's an array.

This breaks code because `$this->Auth->user()->id` is valid only when it's not from the session.

**Comment by thinkingmedia** [comment]
**Closed**

Entity objects support Array interfaces. Accessing properties as `$this->Auth->user()['id']` avoids the problem.

**Comment by ADmad** [comment]
Auth->user() should always return an array. `HybridAuthAuthenticate` needs to be fixed to return array instead of entity.

**Comment by thinkingmedia** [comment]
I think I had code replacing a view variable with an entity instead of using the `$this->Auth()->user()` value. Looking at the code it does this.

        $result = $table
        ->where($conditions)
        ->hydrate(false)
        ->first();

`hydrate(false)` forces it to an array. So I don't think this bug exists.

**Comment by ADmad** [comment]
Yup, checking the code it does return an array.
