### ISSUE TITLE
[improvement] Add option for fields.

### ISSUE THREAD

**Issue by thinkingmedia** [ADmad/CakePHP-HybridAuth#28]
Right now the plugin stores all of the user record fields in the session. Would be nice if the config could define what fields should be stored.

**Comment by ADmad** [comment]
It's the same as how all other core authenticators work too. The full user record is stored in session (except the password field). I would suggest moving the other fields which you don't need in sessions into a separate profile table.

**Comment by thinkingmedia** [comment]
If that's the standard practise then I'll close this. Just seems kind of heavy to reload extra data for each request.
