### ISSUE TITLE
Is it possible to use both CakePHP default auth with the hybrid Auth?

### ISSUE THREAD

**Issue by vivekdoshi2** [ADmad/CakePHP-HybridAuth#30]
Right now I am working on project where we need facebook and twitter login.
And I have also configure the login in my project but now its not authenticate with simple username and password.

This is AppController.php
```
class AppController extends Controller
{
    public function initialize()
    {
            $this->loadComponent('Flash');
            $this->loadComponent('Auth', [     
                'loginRedirect' => [
                    'controller' => 'Users',
                    'action' => 'index'
                ],
                'logoutRedirect' => [
                    'controller' => 'Users',
                    'action' => 'login'
                ],
                'authenticate' => [
                        'ADmad/HybridAuth.HybridAuth'
                ]
            ]);        
    }
}
```

Its working with only facebook and twitter login,and please let me know how to store user in database after successful login in fb or twitter.

**Comment by ADmad** [comment]
You can not included FormAuthenticate in your `'authenticate'` list.

**Comment by vivekdoshi2** [comment]
So If I'll use hybrid auth than it is not possible to use cake default auth,right?

**Comment by ADmad** [comment]
You can use both. Read the Cake manual properly to see how to configure and use multiple authenticators.

**Comment by vivekdoshi2** [comment]
I have gone through the doc but didn't get anything useful,can you please send me the link to that article.
That will be very useful me.

**Comment by ADmad** [comment]
http://book.cakephp.org/3.0/en/controllers/components/authentication.html#configuring-authentication-handlers

**Comment by vivekdoshi2** [comment]
Thanks for your help.I'll try to do both authentication.

Thank you very much.

**Comment by vivekdoshi2** [comment]
Hi thanks for your help its solved by below changes

```
public function initialize()
    {
            $this->loadComponent('Flash');
            $this->loadComponent('Auth', [
                'authenticate' => [
                        'Form',
                        'ADmad/HybridAuth.HybridAuth'
                ],
                'loginRedirect' => [
                    'controller' => 'Users',
                    'action' => 'index',
                    'plugin' => false
                ],
                'logoutRedirect' => [
                    'controller' => 'Users',
                    'action' => 'login'
                ]
            ]);        
    }
```
Now can you please help me with user registeration,after successful login?

**Comment by vivekdoshi2** [comment]
Hello?Can you please tell me,how to save user on first time social login?

**Comment by ADmad** [comment]
This is not a help forum. Visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net

Thanks!

**Comment by vivekdoshi2** [comment]
Then please improve the README.md,
so user can easily install your plugin and use all functionality.

Thanks!

**Comment by ADmad** [comment]
Quoting the README:

> If no user is found and registrationCallback option is specified the specified method **from the User model** is called.

**Comment by thinkingmedia** [comment]
Not the greatest project, but the plugin does work.

https://github.com/thinkingmedia/find2cards

@ADmad maybe we need a sample project?

**Comment by ADmad** [comment]
@thinkingmedia I personally don't have the time to make one :)  But I would be happy to link any sample project / detailed tutorial in the README if someone can write one.

**Comment by thinkingmedia** [comment]
@ADmad if we do a sample project then it has to be kept upto date. I think adding to the README for now should be enough. The README should be all the user needs to use the project. If they can't then the README needs to be updated.

**Comment by vivekdoshi2** [comment]
Hello I have made that,I have configured it in my project

I can make you the sample project with detail description if you want.

Thanks.

**Comment by ADmad** [comment]
@thinkingmedia The PR you had started for updating the README was on the right path. Once that's merged I don't think a full sample app would be even necessary.
