### ISSUE TITLE
Call to a member function api() on array

### ISSUE THREAD

**Issue by fidel037** [ADmad/CakePHP-HybridAuth#32]
Cant post to page. I got all needed params but when I try to execute $pages->api()->api( "/" . $pages['data'][0]['id'] . "/feed", 'post', $params ); i get 
Call to a member function api() on array

**Comment by ADmad** [comment]
Are you this relates to this hybridauth plugin? What's $pages?

**Comment by fidel037** [comment]
$pages is the array I got from facebook when I requested the pages I manage, and the array of pages is good. The token and page id are good but there is something wrong with the request...

**Comment by ADmad** [comment]
This plugin only handles authentication, unless you have an authentication problem its unrelated to the plugin.

**Comment by fidel037** [comment]
Nope. Auth works fine as I am able to get all tokens and permissions but can't make post request...
