### ISSUE TITLE
Use with multiple Providers per User

### ISSUE THREAD

**Issue by mrnetworks** [ADmad/CakePHP-HybridAuth#33]
Hi,

is it possible to use hybridauth with multiple providers per user? Like an 1:n relationship between users table and providers table?

**Comment by ADmad** [comment]
It should with the db schema you have shown [here](https://github.com/hybridauth/hybridauth/issues/514#issuecomment-125868794). Configure the authenticator to use the Providers table instead of Users and set `contain` so that associated user record is also fetched by AuthComponent.

**Comment by mrnetworks** [comment]
ah, thank you. that works. :)
