### ISSUE TITLE
fields-parameter is missing

### ISSUE THREAD

**Issue by mrnetworks** [ADmad/CakePHP-HybridAuth#34]
Hi,

i started to work with this plugin on CakePHP3 and login works. But the userdata returning from facebook just includes username and id. it not includes i.e. email.

i didn't found a way to set fields-parameter for "/me?fields=..."
is there a way to get this data from your plugin?

**Comment by ADmad** [comment]
[Configure](http://hybridauth.sourceforge.net/userguide/Configuration.html) Facebook provider to fetch email.

**Comment by mrnetworks** [comment]
Hi,

thank you for your answer. i configured your plugin with email scope, but i recieve no email from facebook until i changed line 163 from Hybrid\Providers\Facebook.php to

$data = $this->api->api('/me?fields=id,name,email');

will this change get overwritten by an update?

**Comment by ADmad** [comment]
That file is part of [hybridauth](http://github.com/hybridauth/hybridauth) not my plugin so ask there.

**Comment by damianoporta** [comment]
@mrnetworks is your app live? I had the same problem testing this plugin with a test APP. Put it live you should fix that problem
