### ISSUE TITLE
Authentication does not return correct information

### ISSUE THREAD

**Issue by damianoporta** [ADmad/CakePHP-HybridAuth#36]
Hello,
after login i get few information of the user, this is the output of `$this->Auth->identify()`
```
[
	'identifier' => '102062xxxxxx',
	'webSiteURL' => '',
	'profileURL' => '',
	'photoURL' => 'https://graph.facebook.com/102062xxxxxx/picture?width=150&height=150',
	'displayName' => 'Name Surname',
	'description' => '',
	'firstName' => '',
	'lastName' => '',
	'gender' => '',
	'language' => '',
	'age' => null,
	'birthDay' => null,
	'birthMonth' => null,
	'birthYear' => null,
	'email' => '',
	'emailVerified' => '',
	'phone' => null,
	'address' => null,
	'country' => null,
	'region' => '',
	'city' => null,
	'zip' => null,
	'username' => '',
	'coverInfoURL' => 'https://graph.facebook.com/102062xxxxxx?fields=cover&access_token=xxxxxxx'
]
```
It is strange because i am using this scope `email, public_profile, user_friends`.

When i see the dialog on the facebook's page i correctly see that app is asking for email, public profile and friends, but the result does not have those information. Why?

**Comment by damianoporta** [comment]
Maybe because my app still not live yet?

**Comment by ADmad** [comment]
I am not sure. The issue is not related to my plugin but hybridauth config so check it's docs.

**Comment by ADmad** [comment]
Duplicate of #34
