### ISSUE TITLE
Check if the result is an entity

### ISSUE THREAD

**Issue by damianoporta** [ADmad/CakePHP-HybridAuth#37]
Hello,
we should add another check here: https://github.com/ADmad/CakePHP-HybridAuth/blob/event/src/Auth/HybridAuthAuthenticate.php#L206-L213

if the result is an entity we should `return $result->toArray();` without doing the query again. What do you think?

**Comment by ADmad** [comment]
The query was redone to ensure options like `contain` were applied and `password` was unset. But I guess we could rely on dev to take care of it themselves.

**Comment by ADmad** [comment]
There's  no extra query in 4.x, the entity provided by callback is directly used.
