### ISSUE TITLE
Multi-providers login

### ISSUE THREAD

**Issue by damianoporta** [ADmad/CakePHP-HybridAuth#38]
Hello,
looking at the login page we simple do `$user = $this->Auth->identify();`
The problem here should be if we manage more providers. Because the identify() method calls the provider login page but what if we have many, what happen ?

How should we set the specific provider we need to identify?

**Comment by damianoporta** [comment]
I know we can use an input with the name of the provider, but it does assumes that we are sending post data, we should not send post data if we only need to identify the user. No? Maybe a querystring parameter?

**Comment by ADmad** [comment]
You can set `$this->request->data['provider']` with provider name before calling `Auth->identify()`.

**Comment by damianoporta** [comment]
@ADmad ok works! thanks

**Comment by ADmad** [comment]
The auth adapter now uses GET instead of POST to initiate auth process. Check readme. Basically you just need to create links with provider name like `/users/login?provider=Google`.

**Comment by damianoporta** [comment]
@ADmad Good! :+1:
