### ISSUE TITLE
Email field in social_profiles is useless

### ISSUE THREAD

**Issue by damianoporta** [ADmad/CakePHP-HybridAuth#40]
Hi!
Why should we use the email field inside social_profiles table?
In the users table we already have **email** field. When we use two or more socials we use that field to understand if the user is already registered. `social_profiles.email` is only a "clone" of that field, looks useless to me. What do you think?

**Comment by ADmad** [comment]
Fields in `social_profiles` table are kept in sync with info available from provider. It's meant to have all fields listed [here](http://hybridauth.github.io/hybridauth/userguide/Profile_Data_User_Profile.html) (I have to update the migrations file).

It's possible that user changes his email with provider in future in which case `social_profiles.email` will have the up to date value which could differ from `users.email`. 

That said `id`, `user_id`, `provider`, `identifier` are the only essential fields. You can remove others if you don't need them.
