### ISSUE TITLE
Why adding a new user into Authenticate file?

### ISSUE THREAD

**Issue by damianoporta** [ADmad/CakePHP-HybridAuth#42]
Hi,
looks a bit strange to me adding a new user inside the authenticate file. If i can ask, why this choice? I think we should trigger the `newUser` event and then all the logic must be in the controller.

A new type of authentication should check if it is able to authenticate the user, nothing else.
Do we need a refactorization?

**Comment by ADmad** [comment]
> I think we should trigger the newUser event and then all the logic must be in the controller.

That's [already](https://github.com/ADmad/CakePHP-HybridAuth/blob/4.0/src/Auth/HybridAuthAuthenticate.php#L309) done.

**Comment by damianoporta** [comment]
@ADmad i know there is a `newUser` event, but looking at the file there are different save() on **socialprofiles** and **users**. I am asking why, if we are planning to use that event indeed.

**Comment by ADmad** [comment]
It's a fallback for lazy individuals. I may remove it or move to a separate class.
