### ISSUE TITLE
Callback for HybridAuth.newUser event is never attached

### ISSUE THREAD

**Issue by damianoporta** [ADmad/CakePHP-HybridAuth#44]
I found a problem attaching the method to handle new registrations.
At the moment i have:

```
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
        EventManager::instance()->on('HybridAuth.newUser', [$this, 'socialRegistration']);
    }
```
the problem is that the UsersController is never called, HybridAuthController instead because the provider is calling the **authenticated** method there.

If i put the same beforeFilter inside the AppController it works perfectly, but adding the callback for registration there does not sounds good.

is there any workaround?

**Comment by ADmad** [comment]
You shouldn't me setting up a controller method as callback in the first place. It should be a method of `UsersTable` and the listener can be setup in `UsersTable::initialize()`.

**Comment by ADmad** [comment]
I have updated readme of 4.x showing how to attach the listener
