### ISSUE TITLE
view problem

### ISSUE THREAD

**Issue by sailendraw** [ADmad/CakePHP-HybridAuth#45]
first of all i would like to say sorry for posting such a stupid question, i have download this plugin and loaded to my application and configure my controller and config file as defined, but i cannot see any info that tells my how should i configure my login.ctp file, i tried to implement the src/template/login.ctp code found in the repo but that doesnt work in my app. i cannot see any link that says login with facebook and others. can you please point out to correct doc if any i am using cake 3

**Comment by ADmad** [comment]
Use [4.0](https://github.com/ADmad/CakePHP-HybridAuth/tree/4.0) branch. Readme has required details.

**Comment by sailendraw** [comment]
i am using cake 3.0 and current branch 4.0 is for 3.1, does it support cake 3.0 also ?.
