### ISSUE TITLE
Profile returns not matching passed provider

### ISSUE THREAD

**Issue by davidyell** [ADmad/CakePHP-HybridAuth#52]
**What I'm doing**
* I'm testing my sign in in my browser. 
* I have Google, Facebook and Twitter
* I am using a query param `?provider=Twitter` etc, as detailed in the docs
* I have redirected my live url `example.com` to my `localhost` so that OAuth callback urls resolve correctly.
* I am forcibly using `exit` inside my `createUser()` method to see the web service return and my newly built `UserEntity`.

**What is happening**
After trying Twitter for example, I then refresh my login page and click to sign in with Google, and I get a Twitter response.

**What I'm expecting**
My expectation would be that the return of `$event->data()['profile']` would match the provider passed in the query param.

**What could be happening?**
I've not done too much investigation at this point, but I can only imagine that there is some caching of the web service response somewhere. It's worth noting that this behaviour doesn't happen all the time, and seems to be triggered by sending many request, so could be a side effect of development.

I wanted to raise an issue for a number of reasons. Firstly so that I know I won't forget it. Secondly so if anyone else hits the issue we can collate thoughts, and thirdly to get some input on potential failure points and things to debug.

**Comment by davidyell** [comment]
Clearing my browser cache seems to have solved the issue. So quite likely to be my browser.

**Comment by ADmad** [comment]
An intermittent issue would be difficult to debug. Need a way to reliably reproduce the issue.
