### ISSUE TITLE
Stopped working after upgrading to cakePHP 3.1.4

### ISSUE THREAD

**Issue by leighmackay** [ADmad/CakePHP-HybridAuth#55]
Hello Admad,

First off,  this plugin has been so useful, thank you for making it.

Having an issue since upgrading to the newest version of CakePHP. Now when clicking on login from Google or Facebook, I'm logged in but never get redirect to the provider site and no provider_uid is generated.

![screen shot 2015-11-13 at 12 31 32 pm](https://cloud.githubusercontent.com/assets/10221/11136903/b3deef78-8a02-11e5-81d1-7fd979535a38.png)

Keeps generating users in the database on every click, I've not changed any code and only noticed since upgrading.

Any ideas? I'll set up a blank project and see If I can replicate what is happening.

Thank you.

**Comment by ADmad** [comment]
There have been no changes recently in AuthComponent and it's related classes in core. Maybe something something changed in hybridauth or facebook. Check with a clean setup with another provider and see what happens.

**Comment by leighmackay** [comment]
Thank you, I'll try.

**Comment by leighmackay** [comment]
Hi Admad,

Sorry, it's working perfectly and is awesome! in the upgrade I changed the bootstrap file and did not load the plugin correctly, silly mistake.

thank you for all the work you do on CakePHP and your plugins they have helped me so much.

Have a good day!

Leigh
