### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by burzum** [ADmad/CakePHP-HybridAuth#56]
The documentation of this plugin says to check the examples of the Hybrid Auth docs but there is a red box on the page telling me this:

> Please note that the examples are outdated and not production ready.
> New examples are planned in one of the future releases.

So how do I set this up to work with a few different remote logins? FB, Twitter and Facebook to be specific.

**Comment by burzum** [comment]
The same notice is on http://hybridauth.github.io/hybridauth/userguide/Examples_and_Demos.html.

**Comment by ADmad** [comment]
I don't maintain hybridauth so nothing I can do about it. There's no real need to check those examples anyway. Just check the example login element in this plugin. You just need to post to login action with provider name. The provider configs should be set as shown in http://hybridauth.github.io/hybridauth/userguide/Configuration.html

**Comment by burzum** [comment]
That's what my guess was, I just couldn't find any confirmation for it. So it's simply the adapter name I have to pass in the URL and I'm OK? Need to check the element later today.
