### ISSUE TITLE
Cakephp 2 Hybrid Auth not writing associated models in user session.

### ISSUE THREAD

**Issue by shainanand** [ADmad/CakePHP-HybridAuth#60]
Hybrid auth is not writing associated models of User while doing $this->Auth->login().

**Comment by ADmad** [comment]
Show your Auth config.

**Comment by shainanand** [comment]
'Auth' => array(
            'authorize' => array(
                'Actions' => array('actionPath' => 'controllers')
            ),
      'authenticate' => array(
        'all' => array (
                  'scope' => array('User.status' => 1)
               ),
        'Form' => array(
          'userModel' => 'User',
          'fields' => array('username' => 'email','password' => 'password')
        )
      )
        ),

**Comment by ADmad** [comment]
You haven't set `'contain'` key which ensures associated records are added to session. Read the docs.

**Comment by shainanand** [comment]
But while doing normal Auth login, these associated models are shown in the session data. Only in Hybrid auth session data, associated models are missing.
