### ISSUE TITLE
callbacks/extensionpoints for authenticated action

### ISSUE THREAD

**Issue by dereuromark** [ADmad/CakePHP-HybridAuth#61]
It would be nice to have extension points for HybridAuthController::authenticated().
This way we can execute the same after login logic like the normal login would, or via protected AppController method use the same one for both.

Ideally there is one for the success (e.g. logincounter raise) and one for the error case (e.g. flash message).

**Comment by thinkingmedia** [comment]
I use the identify event which is raised by the AuthComponent. It works for social or form login and is how I tracked things like login counting.

**Comment by ADmad** [comment]
If `Auth.afterIdentify` doesn't cut if for you, you can specify your own action instead of `HybridAuthController::authentication()` by setting `hauth_return_to` config. I have updated the [readme](https://github.com/ADmad/CakePHP-HybridAuth#usage) with info about it.

**Comment by dereuromark** [comment]
Coo, thx!
