### ISSUE TITLE
Instagram Login

### ISSUE THREAD

**Issue by sevkialacatli** [ADmad/CakePHP-HybridAuth#64]
Hi,
I am going to use the version for CakePhp 2.4+ but I am not sure that Instagram login is working properly? As I found some LinkedIn typos in Instagram provider, I've been in doubt if it's working.

Thanks in advance.

**Comment by ADmad** [comment]
The plugin is a wrapper for the HybridAuth lib. You need to check the [HybridAuth](http://hybridauth.github.io/hybridauth/) to find out which providers it supports.
