### ISSUE TITLE
Issue with google login for few users

### ISSUE THREAD

**Issue by abhikakade** [ADmad/CakePHP-HybridAuth#65]
In server error logs: I can see following message

Argument 1 passed to App\Model\Table\UsersTable::createUser() must be an instance of App\Model\Table\Event, instance of Cake\Event\Event given

And socialprofile & users both table dont have entry for these users

**Comment by ADmad** [comment]
Add `use Cake\Event\Event` at top of your file.

**Comment by abhikakade** [comment]
Thanks this helped !!

However now after validation from google end its stuck at below URL:

**hybrid-auth/authenticated#**

and doesnt create profile in social+profile table..
