### ISSUE TITLE
Call to a member function primaryKey() on null 

### ISSUE THREAD

**Issue by koffisani** [ADmad/CakePHP-HybridAuth#66]
After authentication (after first registration), I'm getting this message : 

`Notice (8): Undefined variable: UsersTable [ROOT/vendor/admad/cakephp-hybridauth/src/Auth/HybridAuthAuthenticate.php, line 289]`

> Fatal Error 
> Cake\Error\FatalErrorException

`Error: Call to a member function primaryKey() on null
File /home/user10/public_html/app/vendor/admad/cakephp-hybridauth/src/Auth/HybridAuthAuthenticate.php
Line: 289 `
How to fix this ?

**Comment by ADmad** [comment]
Which provider did you use?  Did the user profile returned by provider include email?

**Comment by koffisani** [comment]
I'm using LinkedIn, Google, Facebook and Twitter.

**Comment by ADmad** [comment]
Do you get same error with all providers or just a particular one?

**Comment by koffisani** [comment]
Yes all the providers I'am using. I remark that the exception is raised when trying to log in again after being registered.

**Comment by ADmad** [comment]
That line of code should never be reached when logging in again. Make sure you are properly creating a new record in your users table the first time a user is authenticated with a provider.

**Comment by ADmad** [comment]
A new release has been done which should hopefully fix this issue.
