### ISSUE TITLE
Plugin Admad/HybridAuth could not be found.

### ISSUE THREAD

**Issue by anujsharma9196** [ADmad/CakePHP-HybridAuth#67]
When I run `bin/cake migrations migrate -p ADmad/HybridAuth` to generate table it gives

```
Plugin Admad/HybridAuth could not be found. in [/var/www/html/site/vendor/cakephp/cakephp/src/Core/Plugin.php, line 148]
```

**Comment by ADmad** [comment]
Are you sure you copy / pasted the exact command?  Because the error message says "Admad" instead of "ADmad" so you must have made a typo somewhere.

**Comment by anujsharma9196** [comment]
yes I have copy pasted the same and it is `Admad` in the error message

**Comment by anujsharma9196** [comment]
![screenshot from 2016-06-30 14-19-00](https://cloud.githubusercontent.com/assets/6560085/16482539/d1b517fe-3ecd-11e6-825b-95cfca4bce72.png)

**Comment by ADmad** [comment]
Jeez man read your own screenshot. It clearly shows your `plugin load` command is incorrect. It has "Admad" instead of "ADmad".

**Comment by anujsharma9196** [comment]
ohh so sorry... but now gives  `bin/cake migrations migrate -p ADmad/HybridAuth`
```
[PDOException]                                                          
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
```
