### ISSUE TITLE
Getting the information from the auth

### ISSUE THREAD

**Issue by Cafnio** [ADmad/CakePHP-HybridAuth#70]
Hi there.

First of all, thanks for this plugin, really great ;)

I'm trying to do something.

So on my Users/login, the users choose which social they want to login.. Lets imagine facebook. They click on it, authorize it and then I want it to redirect to a page where he writes extra information ( I know this is not usual, but it's how the platform is built, and we need some extra information from the user, such as VAT number and such)

I already got the redirect working properly ('hauth_return_to' => 'users/add'). Though, I don't know how in users/add.ctp get the user from social and fullfill my form with some information from 

Thanks a lot!

**Comment by ADmad** [comment]
`$this->Auth->user('social_profile')` will give you facebook profile. So set that info to view.

**Comment by Cafnio** [comment]
It does return null (testing it on the controller).. Doing anything wrong?
