### ISSUE TITLE
mysql table name

### ISSUE THREAD

**Issue by fiction85** [ADmad/CakePHP-HybridAuth#72]
can you change table name from social_profiles to something else?
i tried changing this 'profileModel' => 'ADmad/HybridAuth.SocialProfiles', and this $this->hasMany('ADmad/HybridAuth.SocialProfiles');
but still ain working.
please help

**Comment by ADmad** [comment]
Define "ain working". What error do you get?

**Comment by fiction85** [comment]
never mind, i deleted "ADmad/HybridAuth" in  'profileModel' => 'ADmad/HybridAuth.SocialProfiles',(and somewhere else)  and it works now. but now im getting this strange behavior with facebook login.
![hm](https://cloud.githubusercontent.com/assets/21250962/18006627/b840b5e4-6ba0-11e6-8548-bd77401927b2.jpg)
Why is fb token and id outside of HA store while google is normal?

**Comment by ADmad** [comment]
Those tokens in session are managed by hybridauth lib not by the plugin, so no idea.
