### ISSUE TITLE
Change redirect url with code

### ISSUE THREAD

**Issue by hkosmidi** [ADmad/CakePHP-HybridAuth#73]
I have the following problem.
What I want is that of a user press a link to /baskets/save to redirect him to login and then later on to /baskets/save again. 
In /baskets/save:
if(!$this->Auth->user()) {
            $this->request->session()->write('goto', ['controller' => 'Baskets', 'action' => 'save']);
            return $this->redirect('/users/login');
        }

and in users/login:
if($goto && count($goto) > 1)
          $this->Auth->redirectUrl(array_merge($goto, ['plugin' => false]));

but then I get an error: 
Error: A route matching "array ( 'controller' => 'Users', 'action' => 'login', 'plugin' => 'ADmad/HybridAuth', '_ext' => NULL, )" could not be found. 

The error occurs in HybridAuthController.php on line 50:
if ($user) {
	          $this->Auth->setUser($user);
	          return $this->redirect($this->Auth->redirectUrl());    <------------- here
	       }

What am I doing wrong?

**Comment by ADmad** [comment]
Use `hauth_return_to` option to set the redirection url you want.

**Comment by hkosmidi** [comment]
how can I access it and change it programmatically? I thought you only set it once in AuthComponent initialization

**Comment by ADmad** [comment]
Hmm nvm, trying to change the config after authenticator instance has already been created won't work anyway. You need to figure out yourself how/where the `plugin` get's added to your redirect URL.

Why do you need to manipulate the redirect URL yourself anyway?  Returning back to the URL that was called before login is default behavior.

**Comment by hkosmidi** [comment]
Because I want to redirect to specific actions depending on when the user redirected to login page.
Without the plugin I could do it before. I believe it is a common case scenario.
