### ISSUE TITLE
Listener in UsersTable.php doesn't work

### ISSUE THREAD

**Issue by haghparast** [ADmad/CakePHP-HybridAuth#75]
Hi,
I have a plugin in which I have a Users controller and Model. I followed all the steps you mentioned and added the listener in UsersTable.php of my plugin but when the callback from Google arrives the execption in line 339 of HybridAuthAuthenticate.php is triggered and I see the error : "You must attach a listener for "HybridAuth.newUser" event which saves new user record and returns an user entity."
Could you help me please?

**Comment by ADmad** [comment]
Make sure your `UsersTable` is being loaded. Put a `die()` in your `UsersTable::initialize()` and see if it's executed.

**Comment by haghparast** [comment]
Thanks for the tip but I had done this before posting my comment here. I am an experienced web developer and I tried everything I could before bothering you.

**Comment by ADmad** [comment]
Since your table class is in a plugin did you set `'userModel'` config to `Plugin.Users`?

**Comment by haghparast** [comment]
I didn't find any place to set the config for userModel. I traced your code and saw that you used $this->_config['userModel'] on line 99 of HybridAuthAuthenticate.php and since it is directly using the TableRegistry::get, it works with the database table name. 
Is it possible for you to modify your code so that I can use the event like standard cake php events like afterSave and I just add a function to my controller to be triggered after the event in your code is dispatched.

**Comment by ADmad** [comment]
> I didn't find any place to set the config for userModel. I traced your code and saw that you used $this->_config['userModel'] on line 99 of HybridAuthAuthenticate.php and since it is directly using the TableRegistry::get, it works with the database table name. 

`userModel` is a config in BaseAuthenticate itself and it's usage is documented in the [manual](http://book.cakephp.org/3.0/en/controllers/components/authentication.html#configuring-authentication-handlers). But it I'll document it in the plugin's README for completeness.

CakePHP auto created an instance of `Table` class for the default model `Users` and used your `users` table based on conventions.

> Is it possible for you to modify your code so that I can use the event like standard cake php events like afterSave and I just add a function to my controller to be triggered after the event in your code is dispatched.

Requiring new user creation based on social login is a special case and hence warrants a special event. I don't see any need to change it.

**Comment by haghparast** [comment]
Thanks a lot for your help. It is resolved now. Keep up the nice job.
