### ISSUE TITLE
3.4 support for query string redirects

### ISSUE THREAD

**Issue by dereuromark** [ADmad/CakePHP-HybridAuth#76]
Just a small heads up and reminder ticket once 3.4 becomes beta/stable
We should add support for query string redirects then, so the referrer after login still is applied as so far with session approach.

**Comment by ADmad** [comment]
I'll put it on my todo list but patches are welcome.

**Comment by dereuromark** [comment]
Yeah whoever beats the other one to it :)

**Comment by ADmad** [comment]
Whenever you start leave a comment here, I'll do the same. That way we don't waste time :)

**Comment by dereuromark** [comment]
The dev branch works like a charm. I will close this now then.
