### ISSUE TITLE
Undefine Index provider

### ISSUE THREAD

**Issue by wawanabnan** [ADmad/CakePHP-HybridAuth#78]
Hi Admad,

Authentication not respond. Then I change   HybridAuthAuthenticate.php  on Line : 239

from : $provider = $data[$fields['provider']]; 
with  : $provider=$data['provider'];

I am not sure but it work now.

Great & Simple Plugin
Thank bro.

**Comment by ADmad** [comment]
This means you haven't set the config array for component as mentioned in readme, specifically the 'fields' key. So check the readme again and fix your code.

**Comment by wawanabnan** [comment]
Yes thank
