### ISSUE TITLE
Route does not exist

### ISSUE THREAD

**Issue by creaz35** [ADmad/CakePHP-HybridAuth#79]
Hi =)

```
<?= $this->Html->link(
                    'Login with Facebook',
                    ['controller' => 'Users', 'action' => 'login', '?' => ['provider' => 'Facebook']]
                ); ?>
```

After being authentified by facebook when i go back to the login page and click again on the facebook connexion, i'm getting 

Error: A route matching "array ( 'controller' => 'users', 'action' => 'login', 'prefix' => false, 'plugin' => 'ADmad/HybridAuth', '_ext' => NULL, )" could not be found.

Do i have to setup a route in routes.php ?

The passed context was:

[
	'_base' => '',
	'_port' => '80',
	'_scheme' => 'http',
	'_host' => 'www.myprivatedomain.com',
	'params' => [
		'plugin' => 'ADmad/HybridAuth',
		'controller' => 'HybridAuth',
		'action' => 'authenticated',
		'_ext' => null,
		'pass' => [],
		'_matchedRoute' => '/hybrid-auth/authenticated'
	]
]

**Comment by ADmad** [comment]
Add `'plugin' => false` to the url array.
