### ISSUE TITLE
Google Auth not returning all requested info

### ISSUE THREAD

**Issue by loganbest** [ADmad/CakePHP-HybridAuth#81]
Hi,

I'm currently using this config for Google Auth

`
    return [

    'HybridAuth' => [

        'providers' => [

            'Google' => [

                'enabled' => true,

                'keys' => [

                    'id' => '<id>',

                    'secret' => '<secret>',

                    "scope" => "https://www.googleapis.com/auth/plus.me ",

                    "access_type" => "offline",

                    "hd" => "realdomain.com",

                ]

            ],

            'Facebook' => [

                'enabled' => false,

                'keys' => [

                    'id' => '<facebook-application-id>',

                    'secret' => '<secret-key>'

                ],

                'scope' => 'email, user_about_me, user_birthday, user_hometown'

            ],

            'Twitter' => [

                'enabled' => false,

                'keys' => [

                    'key' => '<twitter-key>',

                    'secret' => '<twitter-secret>'

                ],

                'includeEmail' => true // Only if your app is whitelisted by Twitter Support

            ]

        ],

        'debug_mode' => Configure::read('debug'),

        'debug_file' => LOGS . 'hybridauth.log',

    ]

];`

But Google is only returning this object:

`
            [profile] => ADmad\HybridAuth\Model\Entity\SocialProfile Object

                (

                    [provider] => Google

                    [identifier] => identifierhere

                    [website_url] =>

                    [profile_url] =>

                    [photo_url] => urlphotohere

                    [display_name] =>

                    [description] =>

                    [first_name] =>

                    [last_name] =>

                    [gender] =>

                    [language] =>

                    [age] =>

                    [birth_day] => 0

                    [birth_month] => 0

                    [birth_year] => 0

                    [email] => logan@realdomain.com

                    [email_verified] => logan@realdomain.com

                    [phone] =>

                    [address] =>

                    [country] =>

                    [region] =>

                    [city] =>

                    [zip] =>

                    [job_title] =>

                    [organization_name] =>

                    [[new]] => 1

                    [[accessible]] => Array

                        (

                            [*] => 1

                        )`
Why am I not getting the rest of the info? When I use the Google Oauth2 Playground with the same scope I get all of this info, but I can't seem to get it at all via the plugin.

**Comment by ADmad** [comment]
Fetching the profile info from provider is handled by the HybridAuth lib, my plugin just handles authentication in Cake. 

Check the contents of profile object returned by HybridAuth lib by debugging `$event->data()['profile']` in your `UsersTable::createUser()` method. If the data you expect is you expect is not present there itself than issue is with HybridAuth lib (or your config).

**Comment by loganbest** [comment]
Yea it's the same as the object I provided above. I'll create an issue over there and see what happens.
