### ISSUE TITLE
Plugin ADmad/HybridAuth could not be found. in [/var/www/html/redchair/vendor/cakephp/cakephp/src/Core/Plugin.php

### ISSUE THREAD

**Issue by sahdev0** [ADmad/CakePHP-HybridAuth#82]
I am using hybridauth in my application but when i run migration command from command line it gives me following error:

**Exception: Plugin ADmad/HybridAuth could not be found**

**Comment by ankitkumarbhagat** [comment]
Facebook SDK return error : SSL connect error

**Comment by ADmad** [comment]
> Exception: Plugin ADmad/HybridAuth could not be found

You need to first load the plugin in bootstrap.

**Comment by sahdev0** [comment]
I have solved this error and now i can sign-in with facebook with hybrid-auth. Actually it was miss spelling of ADmad/HybridAuth. In Doc admad mentioned it how it can be done.

Thanks to all for try this problem.
