### ISSUE TITLE
Hi in model ok ..? hasMany o belongsTo add field Users.social_profiles_id..?

### ISSUE THREAD

**Issue by EOM** [ADmad/CakePHP-HybridAuth#85]
Hi is Ok ..?
ADmad/HybridAuth.SocialProfiles is hasMany or belongsTo

// Plugin Social HybridAuth.SocialProfiles
        $this->hasMany('ADmad/HybridAuth.SocialProfiles');

Or ok not is ..?
// add field Users.social_profiles_id
 $this->belongsTo('ADmad/HybridAuth.SocialProfiles');

**Comment by ADmad** [comment]
`Users` hasMany `ADmad/HybridAuth.SocialProfiles`
