### ISSUE TITLE
Where should be code fired during login?

### ISSUE THREAD

**Issue by maliawelli** [ADmad/CakePHP-HybridAuth#86]
As you said in documentation, bussiness logic which is after $this->Auth->identify(); in funcrion login is not fired. I've got here code checking if user is banned and some other logic. Where should I put my code now to fire it during login?

**Comment by ADmad** [comment]
If you want to check something after login use the `Auth.afterIdentify` event. 

Or you can extend the `HybridAuthController` provided in the plugin and override [authenticate](https://github.com/ADmad/CakePHP-HybridAuth/blob/master/src/Controller/HybridAuthController.php#L47). Be sure to set `'hauth_return_to'` to your controller action in that case.
