### ISSUE TITLE
Use this plugin combined with normal users (email + pass)

### ISSUE THREAD

**Issue by Tomicapo** [ADmad/CakePHP-HybridAuth#87]
Once logged in with a regular user and password, how do I associate a social profile to the currently logged in user?

**Comment by Tomicapo** [comment]
Ok, sorry, already found out. Simply added another [Authentication Handler in the Auth config array](https://book.cakephp.org/3.0/en/controllers/components/authentication.html#configuring-authentication-handlers).

**Comment by timstermatic** [comment]
Hey @Tomicapo do you have an example of how you achieved this?

I get newUser issues with Twitter even though my user is already logged in.

Cheers.

**Comment by Tomicapo** [comment]
Yes. But first check if you have enabled "Request email addresses from users" in the Twitter App permissions tab. If you're not getting the email from Twitter, I suppose it will be a problem.

```PHP
// AppController.php
// public function initialize()
$this->loadComponent('Auth', [
	'authenticate' => [
		'Form' => [
			'fields' => ['username' => 'email', 'password' => 'password']
		],
		'ADmad/HybridAuth.HybridAuth' => [
			'fields' => [
				'provider' => 'provider',
				'openid_identifier' => 'openid_identifier',
				'email' => 'email'
			],
			'profileModel' => 'ADmad/HybridAuth.SocialProfiles',
			'profileModelFkField' => 'user_id',
			'hauth_return_to' => null,
		],
	],
	'authError' => 'Necesitamos tus datos de ingreso',
	'authorize' => ['Controller'],
]);
```

I tried this:
- Logged in with regular user (via register/add)
- Clicked the Twitter login button (users/login?provider=Twitter)
- After logging in, I checked the database and my normal user was not changed and the social profile row was added correctly.
