### ISSUE TITLE
Wrong country info using Facebook provider

### ISSUE THREAD

**Issue by Tomicapo** [ADmad/CakePHP-HybridAuth#88]
In file: hybridauth\Hybrid\Providers\Facebook.php line: 172 the following line should be as stated below:

```php
$this->user->profile->country = trim($regionArr[1]);`
```

```php
`$this->user->profile->country = trim(end($regionArr));`
```

What changes is the $regionArr key from 1 to the last one. At least in my case, Facebook returns the info in such way that the 2nd array value ($regionArr[1]) is the city and not the country. So to make sure we're getting the country, why not simply use the last value? 

Any other thoughts?

**Comment by ADmad** [comment]
I don't maintain the Hybridauth lib. You need to post the issue on it's own repo https://github.com/hybridauth/hybridauth
