### ISSUE TITLE
Facebook SDK returned an error: Connection timed out after 10000 milliseconds

### ISSUE THREAD

**Issue by hitesh1989** [ADmad/CakePHP-HybridAuth#89]
Facebook SDK returned an error: Connection timed out after 10000 milliseconds

**Comment by ADmad** [comment]
If attempt to communicate with provider times out there's nothing the plugin can do.

**Comment by hitesh1989** [comment]
there must be a curl timeout in plugin

**Comment by ADmad** [comment]
The actual communication with auth providers is done by the [HybridAuth](https://github.com/hybridauth/hybridauth) lib so you should inquire there. This plugin is just a bridge for using that lib with AuthComponent.
