### ISSUE TITLE
 Undefined index: providers error 

### ISSUE THREAD

**Issue by Programmer321** [ADmad/CakePHP-HybridAuth#95]
hi,
I am triyng to log in with google but i have an error that shows every time:
Undefined index: providers [ROOT\vendor\hybridauth\hybridauth\hybridauth\Hybrid\Auth.php, line 298]

any help?
thank you.

**Comment by ADmad** [comment]
Create proper [config](https://github.com/ADmad/CakePHP-HybridAuth/blob/master/README.md#configuration) file.

**Comment by Programmer321** [comment]
I have aready created a config file but i have a question what path should we use in the base_url and should i create a new config file or is it the one in  \vendor\admad\cakephp-hybridauth\config\hybridauth.php.
