### ISSUE TITLE
Google OAuth 2 authorization - Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by TechFanDan** [ADmad/CakePHP-HybridAuth#97]
The URL specified in Google's error page is registered in the API. I've waited for at least half an hour before trying again, but get the same error. Even retried in an incognito windows.

The URL that Google claims isn't in the API, but I copied and pasted after the first error is:
http://mydomain.com/myapp/hybrid-auth/endpoint

I found this SO post, that shows a few way to resolve this issue, however, it keeps occurring.
https://stackoverflow.com/questions/11485271/google-oauth-2-authorization-error-redirect-uri-mismatch

I'm not sure if there would be something specific with this plugin that I'm missing?

**Comment by ADmad** [comment]
Make sure you are using latest version of the plugin and latest 2.9.1 release of Hybridauth. If you are still having problems open an issue on hybridauth/hybridauth repo.
