### ISSUE TITLE
broken release - heads up

### ISSUE THREAD

**Issue by dereuromark** [ADmad/CakePHP-HybridAuth#99]
for people:
DO NOT upgrade to 2.9.2 - it is a broken release regarding facebook login and will fatal error when trying to login. Just cost me a few users being angry.. :/
Stick to 2.9.1 until this is resolved.
See https://github.com/hybridauth/hybridauth/pull/760#issuecomment-294325650 and the linked issue.

And they do not have any tests cases, so it seems..

**Comment by ADmad** [comment]
Just to clarify it's the hybridauth lib that's broken not my plugin :)

**Comment by ApacheEx** [comment]
This issue was fixed in https://github.com/hybridauth/hybridauth/pull/776 (v2.9.3-dev)
